version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/convertkit/stories

    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Run unit tests
          environment:
            SCALYR_WRITE_TOKEN: "test"
          command: go test -v ./...
